<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gxml</string>
		<string>xml</string>
	</array>
	<key>firstLineMatch</key>
	<string>^&lt;\?xml </string>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>keyEquivalent</key>
	<string>^~X</string>
	<key>name</key>
	<string>GopherMarkup</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;\?)\s*([-_\p{Alnum}]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.preprocessor.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string> ([a-zA-Z-]+)</string>
					<key>name</key>
					<string>entity.other.attribute-name.xml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doublequotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotedString</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;!)(DOCTYPE)\s+([:\p{Alpha}_][:\p{Alnum}_.-]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.doctype.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.documentroot.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\s*(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.sgml.doctype.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#internalSubset</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;[!%]--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--%?&gt;</string>
			<key>name</key>
			<string>comment.block.xml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;)((?:([-_\p{Alnum}]+)((:)))?([-_\p{Alnum}:]+))(?=(\s[^&gt;]*)?&gt;&lt;/\2&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.namespace.xml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.namespace.xml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)(&lt;)(/)(?:([-_\p{Alnum}]+)((:)))?([-_\p{Alnum}:]+)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.xml meta.scope.between-tag-pair.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.xml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.namespace.xml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.namespace.xml</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.no-content.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.namespace.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.namespace.xml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.go</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\z</string>
			<key>name</key>
			<string>comment.line.double-slash.go</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.go</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.go</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.go</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.go</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.raw.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.gotemplate</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%@</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.java-props.embedded.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>page|include|taglib</string>
					<key>name</key>
					<string>keyword.other.page-props.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;%[!=]?(?!--)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!--)%&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.java.embedded.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;!\[CDATA\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>]]&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.unquoted.cdata.xml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|nil|iota)\b</string>
			<key>name</key>
			<string>constant.language.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((\d+\.(\d+)?([eE][+-]?\d+)?|\d+[eE][+-]?\d+|\.\d+([eE][+-]?\d+)?)i?)\b</string>
			<key>name</key>
			<string>constant.numeric.floating-point.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+i|0[xX][0-9A-Fa-f]+|0[0-7]*|[1-9][0-9]*)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'(?:[^'\\]|\\(?:\\|[abfnrtv']|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3}))'</string>
			<key>name</key>
			<string>constant.other.rune.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bool|byte|complex(64|128)|error|float(32|64)|rune|string|u?int(8|16|32|64)?|uintptr)\b</string>
			<key>name</key>
			<string>storage.type.go</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>A subset of keyword.other.go for flow control keywords.</string>
			<key>match</key>
			<string>\b(break|case|continue|default|defer|else|for|go|goto|if|range|return|select|switch)\b</string>
			<key>name</key>
			<string>keyword.control.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|case|chan|const|continue|default|defer|else|fallthrough|for|func|go|goto|if|import|interface|map|package|range|return|select|struct|switch|type|var)\b</string>
			<key>name</key>
			<string>keyword.other.go</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.go</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.initialize.go</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>This matches the 'x := 0' style of variable declaration.</string>
			<key>match</key>
			<string>(?:[[:alpha:]_][[:alnum:]_]*)(?:,\s+[[:alpha:]_][[:alnum:]_]*)*\s*(:=)</string>
			<key>name</key>
			<string>meta.initialization.short.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(\Afunc|...\))\s)\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(\sfunc|....\))\s)\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(struct|object|main|init|header|key|var|gos|timer|timers|method|methods|end|endpoints|web|tmpl|output|template|port|deploy)/gi</string>
			<key>name</key>
			<string>entity.name.function.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\Atype\s)\b(\w+)\b</string>
			<key>name</key>
			<string>entity.name.type.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\stype\s)\b(\w+)\b</string>
			<key>name</key>
			<string>entity.name.type.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(append|cap|close|complex|copy|delete|imag|len|make|new|panic|print|println|real|recover)\b</string>
			<key>name</key>
			<string>support.function.builtin.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>support.function.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;-)</string>
			<key>name</key>
			<string>keyword.operator.channel.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;|&lt;=|&gt;|&gt;=)</string>
			<key>name</key>
			<string>keyword.operator.comparison.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&amp;&amp;|[|]{2}|!)</string>
			<key>name</key>
			<string>keyword.operator.logical.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([+]{2})</string>
			<key>name</key>
			<string>keyword.operator.increment.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(--)</string>
			<key>name</key>
			<string>keyword.decrement.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|(?:[+]|-|[|]|^|[*]|/|%|&lt;&lt;|&gt;&gt;|&amp;|&amp;^)=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([+]|-|[*]|/|%|&amp;|[|]|^|&amp;^|&lt;&lt;|&gt;&gt;)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(;)</string>
			<key>name</key>
			<string>keyword.operator.semi-colon.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(,)</string>
			<key>name</key>
			<string>punctuation.definition.comma.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([.])</string>
			<key>name</key>
			<string>punctuation.definition.dot.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:)</string>
			<key>name</key>
			<string>punctuation.definition.colon.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[|\]|{|}|\(|\))</string>
			<key>name</key>
			<string>punctuation.definition.bracket.go</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tagStuff</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bare-ampersand</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>EntityDecl</key>
		<dict>
			<key>begin</key>
			<string>(&lt;!)(ENTITY)\s+(%\s+)?([:\p{Alpha}_][:\p{Alnum}_.-]*)(\s+(?:SYSTEM|PUBLIC)\s+)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.entity.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.entity.xml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.entity.xml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.entitytype.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doublequotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotedString</string>
				</dict>
			</array>
		</dict>
		<key>bare-ampersand</key>
		<dict>
			<key>match</key>
			<string>&amp;</string>
			<key>name</key>
			<string>invalid.illegal.bad-ampersand.xml</string>
		</dict>
		<key>doublequotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bare-ampersand</string>
				</dict>
			</array>
		</dict>
		<key>entity</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.xml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&amp;)([:\p{Alpha}_][:\p{Alnum}_.-]*|#[0-9]+|#x\h+)(;)</string>
			<key>name</key>
			<string>constant.character.entity.xml</string>
		</dict>
		<key>internalSubset</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>name</key>
			<string>meta.internalsubset.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#EntityDecl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameterEntity</string>
				</dict>
			</array>
		</dict>
		<key>parameterEntity</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.xml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(%)([:\p{Alpha}_][:\p{Alnum}_.-]*)(;)</string>
			<key>name</key>
			<string>constant.character.parameter-entity.xml</string>
		</dict>
		<key>singlequotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.xml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.xml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bare-ampersand</string>
				</dict>
			</array>
		</dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|[abfnrtv'"]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3})</string>
					<key>name</key>
					<string>constant.character.escape.go</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.go</string>
				</dict>
			</array>
		</dict>
		<key>string_placeholder</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)%
(\d+\$)?                                    # field (argument #)
[#0\- +']*                                  # flags
[,;:_]?                                     # separator character (AltiVec)
((-?\d+)|\*(-?\d+\$)?)?                     # minimum field width
(\.((-?\d+)|\*(-?\d+\$)?)?)?                # precision
[diouxXDOUeEfFgGaAcCsSqpnvtTbyYhHmMzZ%]     # conversion type</string>
					<key>name</key>
					<string>constant.other.placeholder.go</string>
				</dict>
			</array>
		</dict>
		<key>tagStuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.namespace.xml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.xml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.xml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.localname.xml</string>
						</dict>
					</dict>
					<key>match</key>
					<string> (?:([-_\p{Alnum}]+)((:)))?([-_\p{Alnum}]+)=</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doublequotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotedString</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gxml</string>
	<key>uuid</key>
	<string>c148a1ad-57b9-4a9f-87e5-76cdac2610ee</string>
</dict>
</plist>
